name: Hazardous NEOs 4x Daily

on:
  schedule:
    - cron: "0 0,6,12,18 * * *" # 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:

concurrency:
  group: neos-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          fi

      - name: Run updater
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          OUT_FILE: data/hazardous_neos/latest.json
        run: python -m scripts.update_hazardous_neos

      - name: Plan intercepts
        env:
          OUT_FILE: data/hazardous_neos/latest.json
        run: |
          python -m scripts.neo_intercept_planner \
            --output data/hazardous_neos/latest_intercept.json \
            --roll-past

      - name: Commit & push if changed
        env:
          GIT_AUTHOR_NAME: "Matthew Cranny"
          GIT_AUTHOR_EMAIL: "163694578+mcranny@users.noreply.github.com"
          GIT_COMMITTER_NAME: "Matthew Cranny"
          GIT_COMMITTER_EMAIL: "163694578+mcranny@users.noreply.github.com"
        run: |
          git config user.name "${GIT_COMMITTER_NAME}"
          git config user.email "${GIT_COMMITTER_EMAIL}"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Update hazardous NEO snapshot & intercepts (roll-past): $(date -u +%F)"
            git push
          else
            echo "No changes to commit."
          fi
