name: Hazardous NEOs 4x Daily

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # 4x daily (UTC)
  workflow_dispatch:

concurrency:
  group: neos-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check
        run: |
          python -c "import requests, dateutil, dotenv; print('Deps OK')"

      - name: Run updater (NeoWs → latest.json)
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          OUT_FILE: data/hazardous_neos/latest.json
        run: |
          python -m scripts.update_hazardous_neos

      - name: Plan intercepts (→ latest_intercept.json)
        env:
          OUT_FILE: data/hazardous_neos/latest.json
        run: |
          python -m scripts.neo_intercept_planner --output data/hazardous_neos/latest_intercept.json --roll-past

      - name: Commit & push if changed
        env:
          GIT_AUTHOR_NAME: "Matthew Cranny"
          GIT_AUTHOR_EMAIL: "163694578+mcranny@users.noreply.github.com"
          GIT_COMMITTER_NAME: "Matthew Cranny"
          GIT_COMMITTER_EMAIL: "163694578+mcranny@users.noreply.github.com"
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "${GIT_COMMITTER_NAME}"
            git config user.email "${GIT_COMMITTER_EMAIL}"
            git add -A
            git commit -m "CI: update hazardous NEO snapshot & intercepts $(date -u +'%Y-%m-%d %H:%MZ')"
            git push
          else
            echo "No changes to commit."
          fi
